apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: backend 
  template: 
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: nsengiyunva2021/backend:v1
          ports:
          - containerPort: 9001
          env:
          - name: NODE_ENV
            value: PRODUCTION
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits: 
              memory: "512Mi"
              cpu:  "500m"



